<h1 style="margin-bottom:0"><center>DI 501 - Introduction to Data Informatics</center></h1>
<h2 style="margin-top:0"><center>Assignment #1</center></h2>
<h3 style="margin-top:0"><center>Due: October 31, Monday 23:59</center></h3>
<br>
<p style="margin-top:0"><center><b>This assignment is prepared for Middle East Technical University's DI 501 - Introduction to Data Informatics course.</b></center></p>
<hr style="height:2px;color:navy;margin-top:0">
<p style="margin-top:0; text-align: justify; font-size:15px">This assignment consists of two distinct sections that you need to do required actions by writing Python code. <ul>This assignment will help you:
    <li>Getting familiar with Python & Jupyter Notebook.</li>
<li>Using NumPy and use functions on arrays.</li>
<li>Using Pandas dataframes to import, clean and query data.</li></ul></p>

### Submission and Grading Policy
- Submit your assignments to the corresponding assignment link in https://odtuclass.metu.edu.tr.
- Solutions should be submitted in a single **ipynb** file named: metu-username_HW_1.ipynb (e.g., “e123456_HW_1.ipynb”).
- Late submissions will be accepted by November 3, 2021, 23:59 with a 5% per day penalty.
- Do not change variable names in the code blocks and the texts in the markdowns.
- **<font color=#C91414>This is an individual assignment. Please do not collaborate. You have to adhere to the academic integrity principles.</font>** 
- If needed, you are required to explain your reasonings by adding new blocks below your codes.

<h3 style="margin-bottom:0">a) NumPy</h3>

<h4 style="margin-bottom:0">1) Importing NumPy</h4>

Here, please import NumPy library of Python. You may also import any other library that you intend to use here.

In [1]:
import numpy as np

<h4 style="margin-bottom:0">2) Creating Array</h4>

Create an array (4x4) named "array" that has consecutive numbers from 1 to 16.

In [2]:
array = np.arange(1, 17).reshape(4,4)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

Check the shape of the array to make sure you created it correctly.

In [3]:
assert array.shape == (4,4)
array.shape

(4, 4)

<h4 style="margin-bottom:0">3) Indexing and Slicing</h4>

First, from your array, retrieve elements "10,11 and 12".

In [4]:
array[2, 1:]

array([10, 11, 12])

Now, retrieve all elements that are greater than 9.

In [5]:
array[array > 9]

array([10, 11, 12, 13, 14, 15, 16])

Now, retrieve all odd numbers.

In [6]:
array[array % 2 != 0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

Finally, retrieve all numbers that are at the edges of your array (1, 4, 13 and 16).

In [7]:
array[(0,0,-1,-1), (0,-1,0,-1)]

array([ 1,  4, 13, 16])

<h4 style="margin-bottom:0">4) Array Manipulation</h4>

First, delete the last <b>row </b>.

In [11]:
array = np.delete(array, -1, axis=0)
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Now, add a new <b> column </b> that has elements 17, 18 and 19.

In [14]:
array = np.append(array, np.array([17, 18, 19]).reshape(3,1), axis=1)
array

array([[ 1,  2,  3,  4, 17],
       [ 5,  6,  7,  8, 18],
       [ 9, 10, 11, 12, 19]])

<h3 style="margin-bottom:0">b) Pandas</h3>

For understanding pandas library, we will be utilizing a dataset prepared for this assignment. This dataset shows fictional transactions between fictional companies that sell <b> Qutrian </b> (a made up metal) in 2020. Each individual elements are explained as follows:
<ul>
<li>Seller: seller company name</li>
<li>Buyer: buyer company name</li>
<li>Quantity: selling quantity (in tons), can be from 0 to 800 due to limitations.</li>
<li>Price: selling price (in $), can be from 0 to 10 due to limitations.</li>
<li>Date: transaction date, have to be in 2020.</li></ul>



<h4 style="margin-bottom:0">1) Import Pandas</h4>

Here, please import Pandas library of Python. You may also import any other library that you intend to use here.

In [16]:
import pandas as pd

<h4 style="margin-bottom:0">2) Import Data</h4>

Import the "data.csv" file here. You can check how the data is prepared by taking a look at Excel file. Be sure to use correct delimiter while exporting CSV file. Name your dataframe as "df".

In [17]:
df = pd.read_csv('./data.csv', sep='/')
df

seller             buyer  quantity         price   date
0     Qutrian Engineered  Qutrian All-Star     110.0  1.769704e+13  43831
1                  Diluc     Qutrian Force     477.0  2.679111e+14  43831
2                  Cygen          Qutrianx     722.0  1.255434e+14  43831
3         Iconic Qutrian             Grids     779.0  2.887408e+14  43831
4            USA Qutrian      Qutrian Gold     750.0  3.522572e+14  43832
...                  ...               ...       ...           ...    ...
3142              Origin     Japan Qutrian     496.0  7.950121e+14  44196
3143     Qutrian Network   Qutrian Crusade     404.0  3.946285e+14  44196
3144         Qutrianzoid             Omega     380.0  1.602037e+14  44196
3145               Cygen             Bliss     360.0  5.474980e+14  44196
3146    Qutrian All-Star             Omega     702.0  2.036948e+14  44196

[3147 rows x 5 columns]

To look at whether you have correctly imported data, please have a look at top 5 row of your pandas dataframe.

In [18]:
df.head(5)

seller             buyer  quantity         price   date
0  Qutrian Engineered  Qutrian All-Star     110.0  1.769704e+13  43831
1               Diluc     Qutrian Force     477.0  2.679111e+14  43831
2               Cygen          Qutrianx     722.0  1.255434e+14  43831
3      Iconic Qutrian             Grids     779.0  2.887408e+14  43831
4         USA Qutrian      Qutrian Gold     750.0  3.522572e+14  43832

<h4 style="margin-bottom:0">3) Cleanse Data</h4>

Before querying, we need to be sure that our data is ready. As a hint, I will show you potential errors that you may encounter with:
<ul>
<li>If you have checked price and date columns above, you may see there is something wrong with them. It seems price information is written as very big numbers (probably they forgot to put a "." after first digit) and date seems strange, perhaps there is a way to convert this Excel format into pandas format.</li>
<li>There may be missing values. You may want to fill out those values with meaningful numbers.</li>
<li>In data explanations above, you may see some limitations. You may want to do something if there is something wrong with numbers in dataset.</li>

<h5 style="margin-bottom:0">i) Price & Date</h5>

As mentioned above, price information seems strange. This is because they forgot to put a dot after first digit. Also, even if this was a correct column, there would be a huge amount of decimal points that is not necessary in our analysis. So, 3 decimal points is enough for us. After transformation, show your first 5 line to see whether price is transformed correctly.
<br>

<p><i><b>Hint: you may want to use df.apply(lambda ...)</b></i></p>

In [19]:
def parse_price(price):
    if np.isnan(price):
        return price
    s = str(price)
    return float(f'{s[0]}.{s[1:4]}')
df['price']=df['price'].apply(parse_price)
df.head(5)

seller             buyer  quantity  price   date
0  Qutrian Engineered  Qutrian All-Star     110.0  1.769  43831
1               Diluc     Qutrian Force     477.0  2.679  43831
2               Cygen          Qutrianx     722.0  1.255  43831
3      Iconic Qutrian             Grids     779.0  2.887  43831
4         USA Qutrian      Qutrian Gold     750.0  3.522  43832

Then, you may see date information is also strange. This is due to excel date format. You are required to convert this format into ISO 8601 format (yyyy-mm-dd). After transformation, show your first 5 line to see whether date is transformed correctly.

<p><i><b>Hint: xlrd library have functions for date conversions, you can find useful functions here.</b></i></p>

In [98]:
!pip install xlrd

In [20]:
import xlrd

def parse_date(xl_date):
    dt = xlrd.xldate_as_datetime(xl_date, 0)
    return dt.date().isoformat()

df['date']=df['date'].apply(parse_date).astype('datetime64[ns]')
df.head(5)

seller             buyer  quantity  price       date
0  Qutrian Engineered  Qutrian All-Star     110.0  1.769 2020-01-01
1               Diluc     Qutrian Force     477.0  2.679 2020-01-01
2               Cygen          Qutrianx     722.0  1.255 2020-01-01
3      Iconic Qutrian             Grids     779.0  2.887 2020-01-01
4         USA Qutrian      Qutrian Gold     750.0  3.522 2020-01-02

<h5 style="margin-bottom:0">ii) Null Values</h5>

Now, we have converted our strange variables into meaningful ones. Now, we should deal with null values. Before dealing with values, you should have a look at rows with null values to determine what to do with them. Please show us all of the rows that have at least one null value.

In [21]:
df[df.isna().any(axis=1)]

seller               buyer  quantity  price       date
490    Qutrian Trust                 NaN     563.0  5.993 2020-02-28
793   French Qutrian            Qutrianx       3.0    NaN 2020-04-03
1123           Grids         USA Qutrian       NaN  1.149 2020-05-10
1568           Vital            Qutrianx      97.0    NaN 2020-07-02
1649             NaN               Diluc     670.0  2.721 2020-07-11
1783      Queentrian                 NaN     674.0  7.218 2020-07-25
1925            Ca$h               Omega     577.0    NaN 2020-08-09
2053          Vertex                 NaN     348.0  1.585 2020-08-24
2179             NaN     Qutrian Essence     541.0  2.776 2020-09-08
2318           Bliss  Qutrian Engineered     776.0    NaN 2020-09-24
2436  French Qutrian                 NaN     443.0  6.404 2020-10-08
2564             NaN               Diluc     241.0  2.635 2020-10-24
2686   Qutrian Trust                 NaN      63.0  2.399 2020-11-09
2936          Vertex            Qutrianx       5.0    NaN 2020-12-09
3126    Best Qutrian                 NaN     346.0  2.465 2020-12-29

Now, you can only fill null values for "quantity" and "price" as filling "seller" and "buyer" would be very misleading. You can simply use mean values of those columns to fill them out. After filling them, show the rull nows again to ensure only seller or buyer have null values.

In [22]:
df.fillna(df[['quantity', 'price']].mean(), inplace=True)
df[df.isna().any(axis=1)]

seller            buyer  quantity  price       date
490    Qutrian Trust              NaN     563.0  5.993 2020-02-28
1649             NaN            Diluc     670.0  2.721 2020-07-11
1783      Queentrian              NaN     674.0  7.218 2020-07-25
2053          Vertex              NaN     348.0  1.585 2020-08-24
2179             NaN  Qutrian Essence     541.0  2.776 2020-09-08
2436  French Qutrian              NaN     443.0  6.404 2020-10-08
2564             NaN            Diluc     241.0  2.635 2020-10-24
2686   Qutrian Trust              NaN      63.0  2.399 2020-11-09
3126    Best Qutrian              NaN     346.0  2.465 2020-12-29

<h5 style="margin-bottom:0">iii) Limitations</h5>

Finally, to clean the data, we will need to see whether certain entries are below or above limitations. As different types of entries need a different type of corrections, we will consider them separately.

First, let's have a look at whether there is a quantity or price that is off limits. Please show all of the rows that has either off-limit quantity of price.

In [23]:
df[(df['price'] < 0) | (df['price'] > 10) | (df['quantity'] < 0) | (df['quantity'] > 800)]

seller           buyer  quantity  price       date
369      Qutrian Gold           Vista    -118.0 -0.237 2020-02-13
572             Alpha        Qutrianx    -300.0  2.592 2020-03-08
724    German Qutrian  French Qutrian    7777.0  2.925 2020-03-27
1911  Swedish Qutrian    Best Qutrian    1950.0  2.013 2020-08-08
1998  Swedish Qutrian     USA Qutrian     262.0 -0.257 2020-08-18
2504      Qutrian Box        Qutrianx    2231.0  2.828 2020-10-16

There are many things you can do to deal with those values. However, to practice lambda functions, you are required to do the following for quantity and price:
<ul>
<li>If there is a negative number, take absolute value of it (because "minus" sign is most probably an accident) </li>
<li>If there is a number above the limit, simply set it to upper limit.</li>
</ul>

In [24]:
df[['quantity', 'price']] = df[['quantity', 'price']].apply(np.abs)
df['price'].clip(upper=10, inplace=True)
df['quantity'].clip(upper=800, inplace=True)

df[(df['price'] < 0) | (df['price'] > 10) | (df['quantity'] < 0) | (df['quantity'] > 800)]

Empty DataFrame
Columns: [seller, buyer, quantity, price, date]
Index: []

Then, there can be some values for "date" that is not in 2020. First, you need to retrieve them. You can simply sort date value to see extreme values.

In [25]:
np.sort(df['date'].values)

array(['1937-12-20T00:00:00.000000000', '2020-01-01T00:00:00.000000000',
       '2020-01-01T00:00:00.000000000', ...,
       '2020-12-31T00:00:00.000000000', '2023-04-03T00:00:00.000000000',
       '2058-10-16T00:00:00.000000000'], dtype='datetime64[ns]')

There are some dates that are not in 2020. Here, we can simply convert those values into 2020 as they are probably a mistake. After converting, show your sorted date value again to visualize there is not an extreme value anymore.

In [26]:
df['date'] = df['date'].apply(lambda dt: dt.replace(year=2020))
np.sort(df['date'].values)

array(['2020-01-01T00:00:00.000000000', '2020-01-01T00:00:00.000000000',
       '2020-01-01T00:00:00.000000000', ...,
       '2020-12-31T00:00:00.000000000', '2020-12-31T00:00:00.000000000',
       '2020-12-31T00:00:00.000000000'], dtype='datetime64[ns]')

<h4 style="margin-bottom:0">4) Querying Data</h4>

We have cleansed our data as much as we could. In this final step, you will need to query data to get useful information.

First, add a new column that shows revenue (quantity * price) and name it as "revenue", show first 5 columns.

In [27]:
df['revenue'] = df['quantity'] * df['price']
df.head(5)

seller             buyer  quantity  price       date   revenue
0  Qutrian Engineered  Qutrian All-Star     110.0  1.769 2020-01-01   194.590
1               Diluc     Qutrian Force     477.0  2.679 2020-01-01  1277.883
2               Cygen          Qutrianx     722.0  1.255 2020-01-01   906.110
3      Iconic Qutrian             Grids     779.0  2.887 2020-01-01  2248.973
4         USA Qutrian      Qutrian Gold     750.0  3.522 2020-01-02  2641.500

Also, add a new column that indicates the month that the transaction occured and name it as "month". This will help us later. Show first 5 columns.

In [28]:
df['month'] = df['date'].apply(lambda dt: dt.month)
df.head(5)

seller             buyer  quantity  price       date   revenue  \
0  Qutrian Engineered  Qutrian All-Star     110.0  1.769 2020-01-01   194.590   
1               Diluc     Qutrian Force     477.0  2.679 2020-01-01  1277.883   
2               Cygen          Qutrianx     722.0  1.255 2020-01-01   906.110   
3      Iconic Qutrian             Grids     779.0  2.887 2020-01-01  2248.973   
4         USA Qutrian      Qutrian Gold     750.0  3.522 2020-01-02  2641.500   

   month  
0      1  
1      1  
2      1  
3      1  
4      1

Now, you are required to find how much qutrian is sold (in tons) in each month. Then, you are required to sort them by quantity in descending order and show us the top 5 months in terms of total qutrian sold.

<p><i><b>Hint: you may want to use groupby function of pandas.</b></i></p>

In [29]:
df.groupby('month')[['quantity']].sum().sort_values(by='quantity', ascending=False).head(5)

quantity
month               
5      118972.367133
12     116179.000000
7      112796.000000
1      107002.000000
9      106932.000000

Now, you are required to find mean price charged by each of the companies (you can ignore quantities here, just focus on the price). Then, you are required to find 5 cheapest companies and retrieve them.

In [30]:
df.groupby('seller')[['price']].mean().sort_values(by='price', ascending=True).head(5)

price
seller                    
Qutrian Boss      2.436070
Turkish Qutrian   2.823104
Swedish Qutrian   2.835537
Qutrian All-Star  2.842206
Iconic Qutrian    2.884176

Finally, you are required to show the two companies that has the highest total revenue traded (for simplicity, you should consider one way relationships, i.e. all revenue generated from A -> B is different from B -> A, you do not need to add them up).

In [31]:
df.groupby('seller')[['revenue']].sum().sort_values(by='revenue', ascending=False).head(5)

revenue
seller                   
UK Qutrian     126910.971
Qutrian Box    110604.831
Qutrian Corp   104778.670
Qutrian Force  100852.487
Catalyst        96506.957